修复在idea插件中报错：  Caused by: java.lang.NoClassDefFoundError: com/googlecode/aviator/ClassExpression  	at java.base/java.lang.ClassLoader.defineClass1(Native Method)